/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.26).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-02-23T19:11:12.961Z")

@Validated
@Api(value = "driver", description = "the driver API")
@RequestMapping(value = "/v1/")
public interface DriverApi {

    @ApiOperation(value = "Driver assign for delivery", nickname = "driverAssigedToPerticularOrder", notes = "Driver assign to perticular Order", tags={ "Driver assign for delivery", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Order created successfully"),
        @ApiResponse(code = 400, message = "Invalid request") })
    @RequestMapping(value = "/driver/{driverId}/order/{orderId}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> driverAssigedToPerticularOrder(@ApiParam(value = "driver Id in the context path",required=true) @PathVariable("driverId") Integer driverId,@ApiParam(value = "order Id in the context path",required=true) @PathVariable("orderId") Integer orderId,@ApiParam(value = "Metadata about the request { \"requestId\": \"237e9877-e79b-12d4-a765-321741963000\", \"language\": \"en\", \"clientApp\": \"clientAppId provided\", \"requestTime\": \"yyyy-MM-dd HH:mm:ss\"  }" ) @RequestHeader(value="REQUEST-METADATA", required=false) String REQUEST_METADATA,@ApiParam(value = "" ) @RequestHeader(value="X-ENABLE-EXCEPTION-TRACE", required=false) Boolean X_ENABLE_EXCEPTION_TRACE);

}
