version: '3.8'
services:
  mysql-db-uber:
    image: mysql:5.7.37
    container_name: uber-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_CONTAINER_NAME: uber-db
      MYSQL_ROOT_PASSWORD: boca-root-password
      MYSQL_DATABASE: uber
      MYSQL_USER: kerin
      MYSQL_PASSWORD: password123
    networks:
      - spring-boot-uber-network

  activemq-broker-service:
    image: rmohr/activemq
    container_name: activemq-uber
    environment:
      ACTIVEMQ_CONTAINER_NAME: activemq-uber
    ports:
      - "8161:8161"
      - "61616:61616"
    networks:
      - spring-boot-uber-network

  eureka-server-uber:
    container_name: eureka-server-uber
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8761
    ports:
      - "8761:8761"
    networks:
      - spring-boot-uber-network

  driver-consumer-uber:
    container_name: driver-consumer-uber
    build:
      context: ./driver-consumer
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - eureka-server-uber
      - mysql-db-uber
      - activemq-broker-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://uber-db:3306/uber
      SPRING_DATASOURCE_USERNAME: kerin
      SPRING_DATASOURCE_PASSWORD: password123
      EUREKA_SERVER_HOST: eureka-server-uber
      EUREKA_SERVER_PORT: 8761
      ACTIVEMQ_CONTAINER_NAME: activemq-uber
    ports:
      - "8094:8094"
    networks:
      - spring-boot-uber-network
    entrypoint: /bin/sh
    command:
      -c "
      while ! (nc -z eureka-server-uber 8761); do sleep 5; echo 'Waiting for eureka-server-app to start-up...'; done;
      java -jar /app.jar "

  payment-consumer-uber:
    container_name: payment-consumer-uber
    build:
      context: ./payment-consumer
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - eureka-server-uber
      - mysql-db-uber
      - activemq-broker-service
    networks:
      - spring-boot-uber-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://uber-db:3306/uber
      SPRING_DATASOURCE_USERNAME: kerin
      SPRING_DATASOURCE_PASSWORD: password123
      EUREKA_SERVER_HOST: eureka-server-uber
      EUREKA_SERVER_PORT: 8761
      ACTIVEMQ_CONTAINER_NAME: activemq-uber
    ports:
      - "8095:8095"
    entrypoint: /bin/sh
    command:
      -c " while ! (nc -z eureka-server-uber 8761); do sleep 5; echo 'Waiting for eureka-server-app to start-up...'; done;
      java -jar /app.jar "

  soap-server-uber:
    container_name: soap-server-uber
    build:
      context: ./soap-server
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - eureka-server-uber
      - mysql-db-uber
      - activemq-broker-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://uber-db:3306/uber
      SPRING_DATASOURCE_USERNAME: kerin
      SPRING_DATASOURCE_PASSWORD: password123
      EUREKA_SERVER_HOST: eureka-server-uber
      EUREKA_SERVER_PORT: 8761
      ACTIVEMQ_CONTAINER_NAME: activemq-uber
    ports:
      - "8092:8092"
    networks:
      - spring-boot-uber-network
    entrypoint: /bin/sh
    command:
      -c "
      while ! (nc -z eureka-server-uber 8761); do sleep 5; echo 'Waiting for eureka-server-app to start-up...'; done;
      java -jar /app.jar "

  eureka-client-app:
    container_name: eureka-client
    build:
      context: ./eureka-client
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - eureka-server-uber
    environment:
      EUREKA_SERVER_HOST: eureka-server-uber
      EUREKA_SERVER_PORT: 8761
      ACTIVEMQ_CONTAINER_NAME: activemq-uber
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - spring-boot-uber-network
    entrypoint: /bin/sh
    command:
      -c "
      while ! (nc -z eureka-server-uber 8761); do sleep 5; echo 'Waiting for eureka-server-uber to start-up...'; done;
      java -jar /app.jar
      "

  rest-server-uber:
    container_name: rest-server-uber
    build:
      context: ./rest-server
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - eureka-server-uber
      - mysql-db-uber
      - activemq-broker-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://uber-db:3306/uber
      SPRING_DATASOURCE_USERNAME: kerin
      SPRING_DATASOURCE_PASSWORD: password123
      EUREKA_SERVER_HOST: eureka-server-uber
      EUREKA_SERVER_PORT: 8761
      ACTIVEMQ_CONTAINER_NAME: activemq-uber
    ports:
      - "8093:8093"
    networks:
      - spring-boot-uber-network
    entrypoint: /bin/sh
    command:
      -c "
      while ! (nc -z eureka-server-uber 8761); do sleep 5; echo 'Waiting for eureka-server-uber to start-up...'; done;
      java -jar /app.jar "

networks:
  spring-boot-uber-network:
    driver: bridge