cxf.path: /order-service
server.port: 8094
spring.datasource.url: jdbc:mysql://${MYSQL_CONTAINER_NAME:localhost}:3306/${MYSQL_DATABASE:uber}?pinGlobalTxToPhysicalConnection=true
spring.datasource.username: ${MYSQL_USER:root}
spring.datasource.password: ${MYSQL_PASSWORD:kerin3989@K}
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect

#jms.broker.url: tcp://localhost:61616

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/

spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true

spring:
  application:
    name: Driver Consumer
  jpa:
    properties:
      hibernate:
        format_sql: true
  jms:
    template:
      default-destination: delivery_order_queue
  activemq:
    broker-url: tcp://${ACTIVEMQ_CONTAINER_NAME:localhost}:61616
  jta:
    log-dir: ./driver-consumer
    atomikos:
      datasource:
        localTransactionMode: true
        max-pool-size: 10
      properties:
        max-timeout: 9000000
        enable-logging: false