management:
  endpoints:
    web:
      exposure:
        include: '*'

server.port: 9021

spring:
  application:
    name: rest-server
  config.import: optional:configserver:http://localhost:8888/
  #  config.import: optional:configserver:http://root:s3cr3t@localhost:8889