cxf.path: /order-service
server.port: 8092
spring.datasource.url: jdbc:mysql://${MYSQL_CONTAINER_NAME:localhost}:3306/${MYSQL_DATABASE:uber}?pinGlobalTxToPhysicalConnection=true
spring.datasource.username: ${MYSQL_USER:root}
spring.datasource.password: ${MYSQL_PASSWORD:kerin3989@K}
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/

## Configuring info endpoint
info.app.name: soap-server-uber-app
info.app.description: This is soap-server-uber-app
info.app.version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: '*'


jms.broker.url: tcp://localhost:61616

spring.ws.enable: true

spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true

spring:
  datasource:
    initialization-mode: ALWAYS
    data:
      - classpath:data.sql
  application:
    name: SOAP Server
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              MySQL5Dialect:
        format_sql: true
  jms:
    template:
      default-destination: delivery_order_queue
    listener:
      acknowledge-mode: DUPS_OK
  activemq:
    broker-url: tcp://${ACTIVEMQ_CONTAINER_NAME:localhost}:61616
  jta:
    log-dir: ./soap-server
    atomikos:
      datasource:
        localTransactionMode: true
      properties:
        max-timeout: 9000000
        enable-logging: false