calculator.service.non-ssl.address: http://localhost:8092/order-service/orderservice
#cxf.path: /order-service

server.port: 8091
spring.datasource.url: jdbc:mysql://localhost:3306/uber
spring.datasource.username: root
spring.datasource.password: kerin3989@K
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
jms.broker.url: tcp://localhost:61616

spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect